platform :ios, '9.0'

target 'IceCreamShop' do
  use_frameworks!

pod 'Alamofire', '4.4.0'
pod 'Firebase/Core', :inhibit_warnings => true
pod 'Firebase/Database', :inhibit_warnings => true
pod 'Firebase/Auth', :inhibit_warnings => true

end
